global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    env: local

scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: producer-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: consumer-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: redpanda
    static_configs:
      - targets: ["redpanda:9644"]
    metrics_path: /metrics
